// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmbpcsSjSY8j9CzOMhb-mQsU-ZjAj3eDA',
    appId: '1:172492669144:web:4712669ec66c51426617ad',
    messagingSenderId: '172492669144',
    projectId: 'edupeak-studyapp',
    authDomain: 'edupeak-studyapp.firebaseapp.com',
    storageBucket: 'edupeak-studyapp.firebasestorage.app',
    measurementId: 'G-JTS9RT7NJN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWHTjplTxDi6sk0OAteBTtLZJL9bya9c0',
    appId: '1:172492669144:android:f3b1fa06caaf1ea66617ad',
    messagingSenderId: '172492669144',
    projectId: 'edupeak-studyapp',
    storageBucket: 'edupeak-studyapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBO_IcGW_ekHU05xUG4IQBI4ur3Fkf_tcg',
    appId: '1:172492669144:ios:70b807323ad3a1456617ad',
    messagingSenderId: '172492669144',
    projectId: 'edupeak-studyapp',
    storageBucket: 'edupeak-studyapp.firebasestorage.app',
    iosBundleId: 'com.example.edupeak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBO_IcGW_ekHU05xUG4IQBI4ur3Fkf_tcg',
    appId: '1:172492669144:ios:70b807323ad3a1456617ad',
    messagingSenderId: '172492669144',
    projectId: 'edupeak-studyapp',
    storageBucket: 'edupeak-studyapp.firebasestorage.app',
    iosBundleId: 'com.example.edupeak',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmbpcsSjSY8j9CzOMhb-mQsU-ZjAj3eDA',
    appId: '1:172492669144:web:b553e605c6c68f526617ad',
    messagingSenderId: '172492669144',
    projectId: 'edupeak-studyapp',
    authDomain: 'edupeak-studyapp.firebaseapp.com',
    storageBucket: 'edupeak-studyapp.firebasestorage.app',
    measurementId: 'G-NMK7Z5GE58',
  );

}