// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA67zngj-KvGBix6HhzLi0FJO2WwpQxOMk',
    appId: '1:1080878708547:web:1174e96826618eae55e1f6',
    messagingSenderId: '1080878708547',
    projectId: 'edupeak--auth',
    authDomain: 'edupeak--auth.firebaseapp.com',
    storageBucket: 'edupeak--auth.firebasestorage.app',
    measurementId: 'G-3RGPZ2NZR4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjnqiuDhMcZgiCmonwGLmnWKRVlhefj3s',
    appId: '1:1080878708547:android:a358f1fa84b14c7655e1f6',
    messagingSenderId: '1080878708547',
    projectId: 'edupeak--auth',
    storageBucket: 'edupeak--auth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxBEr8xQfzJ-dh6aVFRTVtEDFbnMwkAao',
    appId: '1:1080878708547:ios:ab22c7d6e924455855e1f6',
    messagingSenderId: '1080878708547',
    projectId: 'edupeak--auth',
    storageBucket: 'edupeak--auth.firebasestorage.app',
    iosBundleId: 'com.example.eduPeak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxBEr8xQfzJ-dh6aVFRTVtEDFbnMwkAao',
    appId: '1:1080878708547:ios:20b2cedd575e0c4655e1f6',
    messagingSenderId: '1080878708547',
    projectId: 'edupeak--auth',
    storageBucket: 'edupeak--auth.firebasestorage.app',
    iosBundleId: 'com.example.edupeak',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA67zngj-KvGBix6HhzLi0FJO2WwpQxOMk',
    appId: '1:1080878708547:web:116ee41ef2cbf1c155e1f6',
    messagingSenderId: '1080878708547',
    projectId: 'edupeak--auth',
    authDomain: 'edupeak--auth.firebaseapp.com',
    storageBucket: 'edupeak--auth.firebasestorage.app',
    measurementId: 'G-513EXQKPZT',
  );
}
